name: Run ETL Pipeline Weekly

on:
  schedule:
    - cron: '0 0 * * 5'  # Every Friday at 00:00 UTC
  workflow_dispatch:

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install uv
        run: pip install uv

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('apps/med_llm_offline/pyproject.toml', 'apps/med_llm_offline/uv.lock') }}
          restore-keys: ${{ runner.os }}-uv-

      - name: Install dependencies
        working-directory: apps/med_llm_offline
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e .
          python -m playwright install

      # --- Get the public IP of the GitHub Actions runner ---
      - name: Get public IP
        id: get_ip
        run: |
          echo "ip_address=$(curl -s https://checkip.amazonaws.com)" >> "$GITHUB_OUTPUT"

      # --- Set up MongoDB Atlas CLI ---
      - name: Set up MongoDB Atlas CLI
        uses: mongodb/atlas-github-action@v0.2.0

      # --- Authenticate CLI using env vars ---
      - name: Export Atlas credentials
        run: |
          echo "ATLAS_PUBLIC_API_KEY=${{ secrets.ATLAS_PUBLIC_KEY }}" >> $GITHUB_ENV
          echo "ATLAS_PRIVATE_API_KEY=${{ secrets.ATLAS_PRIVATE_KEY }}" >> $GITHUB_ENV
          echo "ATLAS_PROJECT_ID=${{ secrets.MONGODB_ATLAS_PROJECT_ID }}" >> $GITHUB_ENV

      # --- Whitelist the runner's IP in Atlas ---
      - name: Add GitHub Actions runner IP to MongoDB Atlas IP access list
        run: |
          atlas accessLists create ${{ steps.get_ip.outputs.ip_address }} \
            --type ipAddress \
            --projectId $ATLAS_PROJECT_ID \
            --comment "Temporary access for GitHub Actions runner"

      # --- Run ETL pipeline ---
      - name: Run ETL pipeline
        working-directory: apps/med_llm_offline
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          COMET_API_KEY: ${{ secrets.COMET_API_KEY }}  
          COMET_PROJECT: ${{ secrets.COMET_PROJECT }}  
          MONGODB_DATABASE_NAME: ${{ secrets.MONGODB_DATABASE_NAME }}
        run: |
          source .venv/bin/activate
          python run_etl.py

      # --- Remove GitHub Actions runner IP from Atlas after completion ---
      - name: Remove GitHub Actions runner IP from MongoDB Atlas
        if: always()
        run: |
          atlas accessLists delete ${{ steps.get_ip.outputs.ip_address }} \
            --projectId $ATLAS_PROJECT_ID \
            --force
