name: Run ETL Pipeline Weekly

on:
  schedule:
    - cron: '0 0 * * 5'   # Every Friday at 00:00 UTC
  workflow_dispatch:     # Manual trigger

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install uv
        run: pip install uv

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml', 'uv.lock') }}
          restore-keys: ${{ runner.os }}-uv-

      - name: Install dependencies
        run: uv pip install .

      - name: Run ETL pipeline
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: python apps/med_llm_offline/run_etl.py
