name: Run ETL Pipeline Weekly

on:
  schedule:
    - cron: '0 0 * * 5'  # Every Friday at 00:00 UTC
  workflow_dispatch:

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install uv
        run: pip install uv

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('apps/med_llm_offline/pyproject.toml', 'apps/med_llm_offline/uv.lock') }}
          restore-keys: ${{ runner.os }}-uv-

      - name: Install dependencies
        working-directory: apps/med_llm_offline
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e .
          python -m playwright install

      - name: Install CA certificates (fix SSL issue)
        run: sudo apt-get update && sudo apt-get install -y ca-certificates

      # --- MongoDB Atlas IP Whitelisting ---
      - name: Get GitHub Runner Public IP
        id: get_ip
        run: |
          echo "ip_address=$(curl -s https://checkip.amazonaws.com)" >> "$GITHUB_OUTPUT"

      - name: Set up MongoDB Atlas CLI
        uses: mongodb/atlas-github-action@v0.2.0

      - name: Authenticate MongoDB Atlas CLI
        run: |
          atlas config set public_api_key=${{ secrets.ATLAS_PUBLIC_KEY }}
          atlas config set private_api_key=${{ secrets.ATLAS_PRIVATE_KEY }}
          atlas config set project_id=${{ secrets.MONGODB_ATLAS_PROJECT_ID }}

      - name: Add Runner IP to MongoDB Atlas Access List
        run: |
          atlas accessLists create ${{ steps.get_ip.outputs.ip_address }} \
            --type ipAddress \
            --projectId ${{ secrets.MONGODB_ATLAS_PROJECT_ID }} \
            --comment "Temporary access for GitHub Actions runner"

      - name: Run ETL pipeline
        working-directory: apps/med_llm_offline
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          COMET_API_KEY: ${{ secrets.COMET_API_KEY }}  
          COMET_PROJECT: ${{ secrets.COMET_PROJECT }}  
          MONGODB_DATABASE_NAME: ${{ secrets.MONGODB_DATABASE_NAME }}
        run: |
          source .venv/bin/activate
          python run_etl.py

      - name: Remove Runner IP from MongoDB Atlas Access List
        if: always()
        run: |
          atlas accessLists delete ${{ steps.get_ip.outputs.ip_address }} \
            --projectId ${{ secrets.MONGODB_ATLAS_PROJECT_ID }} --force
