name: Run ETL Pipeline Weekly

on:
  schedule:
    - cron: '0 0 * * 5'  # Every Friday at 00:00 UTC
  workflow_dispatch:

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          pip install uv

      - name: Create .venv and install dependencies
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv pip install -e .

      - name: Run ETL pipeline
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          source .venv/bin/activate
          python apps/med_llm_offline/run_etl.py
